apiVersion: apps/v1
kind: Deployment
metadata:
  name: caliber2022demo
spec:
  selector:
    matchLabels:
      app: caliber2022demo
  replicas: 1
  template:
    metadata:
      labels:
        app: caliber2022demo
    spec:
      containers:
      - name: caliber2022demo
        imagePullPolicy: IfNotPresent
        image: omar10m.azurecr.io/caliber2022demo:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
