apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: caliber2022demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caliber2022demo
  minReplicas: 1
  maxReplicas: 28
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1
    scaleUp:
      stabilizationWindowSeconds: 1
