version: '3'
services:
  caliber2022:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ../
        target: /code
        consistency: consistent
    